version: '3.9'

services:
  web:
    build: .
    container_name: world-of-tethys-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["npm", "start"]
    restart: unless-stopped
